# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gem_fastlane' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gem_fastlane
  pod 'Alamofire'

  target 'gem_fastlane-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gem_fastlaneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
